AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys GitLab databases (TODO - add QS ID)

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9002
        - W9003
        - W9004
        - E0002

Parameters:

# Network Parameters
  VPCID: 
    Type: 'AWS::EC2::VPC::Id'
  VPCCIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
  Subnet1ID:
    Type: 'AWS::EC2::Subnet::Id'
  Subnet2ID:
    Type: 'AWS::EC2::Subnet::Id'

# Database Parameters
  DBEngineVersion:
    AllowedValues: [ '9.6.16', '9.6.17', '9.6.18', '9.6.19', '10.11', '10.12', '10.13', '10.14', '11.6', '11.7', '11.8', '11.9', '12.4']
    MinLength: "4"
    Type: String
  DBName: 
    AllowedPattern: "[a-zA-Z0-9]*"
    MaxLength: "64"
    MinLength: "0"
    Type: String
  DBPraefectName: 
    AllowedPattern: "[a-zA-Z0-9]*"
    MaxLength: "64"
    MinLength: "0"
    Type: String    
  DBUserName: 
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MaxLength: "16"
    MinLength: "1"
    Type: String
  DBPort:
    Type: Number
    MinValue: 1150
    MaxValue: 65535
  DBInstanceClass:
    Type: String

  EnvironmentName:
    Type: String

# Quickstart location Parameters
  QSS3BucketName:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  QSS3BucketRegion:
    Type: String
  QSS3KeyPrefix:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z-/]*$

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources:

# Database security groups
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'Allow access to database port'
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: '-1'
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: !Ref VPCCIDR 
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          IpProtocol: tcp
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub RDSSecurityGroup-${AWS::StackName}
  RDSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt DatabaseSecurityGroup.GroupId
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref DatabaseSecurityGroup
      Description: 'Self Reference'

# PostgreSQL Password

  GitLabDBPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/quickstart/gitlab/${EnvironmentName}/secrets/gitlab-db-password'
      Description: "GitLab DB Password"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUserName}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: "\"@/\\'"
        RequireEachIncludedType: True

  PraefectDBPassword:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/quickstart/gitlab/${EnvironmentName}/secrets/praefect-db-password'
      Description: "Praefect DB Password"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUserName}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: "\"@/\\'"
        RequireEachIncludedType: True

  GitLabDatabase:
    Type: AWS::CloudFormation::Stack
    # E9101 Ignoring 'master' in Aurora PostgreSQL quickstart parameter names
    Metadata: { cfn-lint: { config: { ignore_checks: [E9101] } } }
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-aurora-postgresql/templates/aurora_postgres.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DBEngineVersion: !Ref DBEngineVersion # GitLab PostgreSQL version mappings https://docs.gitlab.com/omnibus/settings/database.html#gitlab-140-and-later
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBMasterUsername: !Sub "{{resolve:secretsmanager:${GitLabDBPassword}:SecretString:username}}"
        DBMasterUserPassword: !Sub "{{resolve:secretsmanager:${GitLabDBPassword}:SecretString:password}}"
        DBPort: !Ref DBPort
        VPCID: !Ref VPCID
        Subnet1ID: !Ref Subnet1ID
        Subnet2ID: !Ref Subnet2ID
        CustomDBSecurityGroup: !GetAtt DatabaseSecurityGroup.GroupId

  PraefectDatabase:
    Type: AWS::CloudFormation::Stack
    # E9101 Ignoring 'master' in Aurora PostgreSQL quickstart parameter names
    Metadata: { cfn-lint: { config: { ignore_checks: [E9101] } } }
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-aurora-postgresql/templates/aurora_postgres.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DBEngineVersion: !Ref DBEngineVersion # GitLab PostgreSQL version mappings https://docs.gitlab.com/omnibus/settings/database.html#gitlab-140-and-later
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBPraefectName
        DBMasterUsername: !Sub "{{resolve:secretsmanager:${PraefectDBPassword}:SecretString:username}}"
        DBMasterUserPassword: !Sub "{{resolve:secretsmanager:${PraefectDBPassword}:SecretString:password}}"
        DBPort: !Ref DBPort
        VPCID: !Ref VPCID
        Subnet1ID: !Ref Subnet1ID
        Subnet2ID: !Ref Subnet2ID
        CustomDBSecurityGroup: !GetAtt DatabaseSecurityGroup.GroupId

Outputs:
  DatabaseSecretName:
    Value: !Ref GitLabDBPassword
  PraefectSecretName:
    Value: !Ref PraefectDBPassword

  GitLabEndpointAddress:
    Value: !GetAtt GitLabDatabase.Outputs.RDSEndPointAddress
  GitLabReadEndpointAddress:
    Value: !GetAtt GitLabDatabase.Outputs.RDSReadEndPointAddress

  PraefectEndpointAddress:
    Value: !GetAtt PraefectDatabase.Outputs.RDSEndPointAddress
